### PR TITLE
Add favorites empty view, fix LegislationFragment leak, add lottie, u…

### LINKED ISSUE #21: When favorites is empty there is a blank view for FavoritesFragment
https://photos.app.goo.gl/QMzjuuHKQN6thvkV6

### PR DESCRIPTION
**Pull request by tpfaff**
…pdate splash screen

resolves #21

### CODE REVIEW

File: app/src/main/java/com/appsontap/bernie2020/legislation/LegislationFragment.kt [hunk 1]
```diff
@@ -139,6 +144,13 @@ class LegislationFragment : BaseFragment() {
         menu.findItem(R.id.action_search).setOnActionExpandListener(expandListener)
     }
 
+    override fun onDestroyOptionsMenu() {
+        super.onDestroyOptionsMenu()
+        expandListener = null
```
Comment (tpfaff) [inline app/src/main/java/com/appsontap/bernie2020/legislation/LegislationFragment.kt]: This fixes the memory leak
